### ISSUE TITLE
ENT ERROR

### ISSUE THREAD

**Issue by Noggo123** [MR-AliHaashemi/LlamaLauncher#1]
Help, why is this wrong i have installed everything and this keeps popping up
https://user-images.githubusercontent.com/98756877/158174000-2c8d26d7-61da-4a0d-9660-97e766effe69.png

**Comment by haashemi** [comment]
Hi @NoggoEU !
seems like `ent` is not installed correctly, or it's not in your $PATH.

try this first:
`go install entgo.io/ent/cmd/ent`

Then open a new terminal (or *maybe* restart your machine) and try again.

If it's still not working, I think you should find and set GOPATH in your env yourself.

**Comment by Noggo123** [comment]
> 

Thx!
