### ISSUE TITLE
Not really an issue But

### ISSUE THREAD

**Issue by NameLord** [MR-AliHaashemi/LlamaLauncher#2]
What is this purpose of this? for connecting to private servers ? for using cheats or ?

**Comment by haashemi** [comment]
Hi @NameLord !

Well, depends on the person who is using it.
Everyone may find it useful for something. (if it even works, 'Cause I didn't tested it for a long time, and I'm not a reverse engineer or something, I just skidded it)

But as a repo owner, I made it to be able to bypass the SSL-Pinning and see/debug the in-game HTTP requests myself.
It could help me and a few others to create better and more secure Fortnite internal API based projects.
